openapi: 3.0.0
info:
  title: Training DTO Definition
  version: 1.0.0

components:
  schemas:
    trainingDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        instructor:
          type: string
      required:
        - id
        - name
        - startDate
        - endDate

paths:
  /training/{id}:
    get:
      summary: Get training by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trainingDTO'
